# Local development environment configuration
services:

  db:
    build:
      context: db
      target: dev
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432

  blobstore:
    build: blobstore
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - 9000:9000
      - 9001:9001
  
  cache:
    build: cache
    ports:
      - 6379:6379
      
  app:
    build: app
    environment:
      PORT: 1337
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    ports:
      - 1337:1337
    depends_on:
      - db
      - blobstore
      - cache
      - search
