services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    expose:
      - 5432
  backend:
    build: backend
    depends_on:
      - database
    ports:
      - 80:80
volumes:
  database-data: