name: node-postgres-template-adoring_mendel
services:
  backend:
    build:
      context: /Users/hong/Projects/node-postgres-template/backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_started
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: node-postgres-template-adoring_mendel
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "1337"
      protocol: tcp
    volumes:
    - type: bind
      source: /Users/hong/Projects/node-postgres-template/backend
      target: /home
      bind:
        create_host_path: true
  database:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
    - "5432"
    image: postgres
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: node-postgres-template-adoring_mendel
    networks:
      default: null
    volumes:
    - type: volume
      source: database-data
      target: /var/lib/postgresql/data
      volume: {}
networks:
  default:
    name: node-postgres-template-adoring_mendel_default
volumes:
  database-data:
    name: node-postgres-template-adoring_mendel_database-data
