services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    expose:
      - 5432
  backend:
    build: backend
    # volumes:
    #   - ./backend:/home
    depends_on:
      - db
    ports:
      - 1337:80
volumes:
  database-data: